import streamlit as st
import pandas as pd

# ==========================================
# 1. ENTERPRISE CONFIGURATION
# ==========================================
st.set_page_config(page_title="Hospital HR Portal", page_icon="🏢", layout="wide")

# 🛡️ STRICT ANTI-THEFT & PRO UI CSS SHIELD
st.markdown("""
    <style>
        /* Hide Header, Footer, and Streamlit Menus */
        #MainMenu, footer, header {visibility: hidden !important;}
        
        /* Hide DataFrame Toolbars (Blocks Download/Search icons above tables) */
        [data-testid="stToolbar"], [data-testid="stElementToolbar"] {visibility: hidden !important; display: none !important;}
        
        /* Disable Text Selection and Copying completely */
        * {
            -webkit-user-select: none !important;
            -moz-user-select: none !important;
            -ms-user-select: none !important;
            user-select: none !important;
        }

        /* Disable Printing (Blocks Ctrl+P) */
        @media print {
            html, body { display: none !important; }
        }

        /* PROFESSIONAL BIG FONT UI STYLING */
        .main-header { font-size: 3rem; color: #1e3a8a; font-weight: 900; margin-bottom: 0px; text-align: center; letter-spacing: 1px;}
        .sub-header { color: #475569; font-size: 1.5rem; margin-bottom: 30px; text-align: center; font-weight: 500;}
        
        /* Top Navigation Menu Styling (Bigger Fonts) */
        div.row-widget.stRadio > div { flex-direction: row; justify-content: center; background-color: #f8fafc; padding: 15px; border-radius: 12px; flex-wrap: wrap; border: 1px solid #e2e8f0; box-shadow: 0 4px 6px rgba(0,0,0,0.05);}
        div.row-widget.stRadio > div > label { margin-right: 20px; padding: 8px 15px; cursor: pointer; font-size: 1.2rem !important; font-weight: bold; color: #1e293b;}
        
        /* Welcome Text Styling */
        .welcome-text { font-size: 5rem; color: #0f172a; font-weight: 900; text-align: center; margin-top: 10vh; letter-spacing: 2px;}
        
        /* Table Search Header */
        .table-title { font-size: 1.8rem; color: #1e3a8a; font-weight: bold; margin-bottom: 10px; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px;}
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 2. STREAMLIT SECRETS AUTHENTICATION
# ==========================================
def check_login():
    if "logged_in" not in st.session_state:
        st.session_state["logged_in"] = False

    if st.session_state["logged_in"]:
        return True

    st.markdown("<br><br>", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 1.5, 1])
    
    with col2:
        st.markdown("<div class='main-header'>🏢 Secure HR Portal</div>", unsafe_allow_html=True)
        st.markdown("<div class='sub-header'>Civil Hospital Establishment Access</div>", unsafe_allow_html=True)
        
        with st.form("login_form"):
            st.markdown("<h3 style='font-size: 1.5rem;'>🔐 Admin Login</h3>", unsafe_allow_html=True)
            input_username = st.text_input("👤 Username")
            input_password = st.text_input("🔑 Password", type="password")
            submit_button = st.form_submit_button("Secure Login", use_container_width=True)

            if submit_button:
                try:
                    SECRET_USER = st.secrets["admin_username"]
                    SECRET_PASS = st.secrets["admin_password"]
                    
                    if input_username == SECRET_USER and input_password == SECRET_PASS:
                        st.session_state["logged_in"] = True
                        st.session_state["current_user"] = input_username
                        st.rerun()
                    else:
                        st.error("❌ Invalid Username or Password.")
                except Exception:
                    st.error("⚠️ Streamlit Secrets set nahi hain.")

    return False

def logout():
    st.session_state["logged_in"] = False
    st.session_state["current_user"] = ""
    st.rerun()

# ==========================================
# 3. DIRECT GOOGLE SHEETS LOADER (CLEAN DATA)
# ==========================================
@st.cache_data(ttl=60)
def load_data_from_sheet(sheet_name):
    SHEET_ID = "1FpDrz63M5Ix_rphXoonZHCDy_PAOUjsrzYIC3AFkUzo"
    csv_url = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
    
    try:
        df = pd.read_csv(csv_url)
        
        # 🎯 EXPERT FIX: 1. Drop completely empty rows
        df = df.dropna(how="all") 
        
        # 🎯 EXPERT FIX: 2. Drop completely empty columns
        df = df.dropna(axis=1, how="all")
        
        # 🎯 EXPERT FIX: 3. Remove "Unnamed" phantom columns generated by empty headers
        df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
        
        if not df.empty:
            df = df.reset_index(drop=True)
            df.index = df.index + 1
        return df
    except Exception as e:
        return pd.DataFrame({"System Alert": [f"⚠️ Error: Data for '{sheet_name}' is unavailable."]})

# ==========================================
# 4. ADVANCED PAGE DESIGNS (WITH SEARCH)
# ==========================================
def render_smart_table(df, title):
    st.markdown(f"<div class='table-title'>{title}</div>", unsafe_allow_html=True)
    
    if "System Alert" in df.columns or df.empty:
        st.dataframe(df, use_container_width=True)
        return
        
    st.markdown(f"<p style='font-size: 1.2rem; color: gray;'><strong>Total Records Found:</strong> {len(df)}</p>", unsafe_allow_html=True)
    search_query = st.text_input("🔍 Search (Type name, ID, or any detail...)", "")
    
    st.markdown("<br>", unsafe_allow_html=True)
    
    if search_query:
        mask = df.astype(str).apply(lambda x: x.str.contains(search_query, case=False)).any(axis=1)
        filtered_df = df[mask]
        st.dataframe(filtered_df, use_container_width=True, hide_index=False)
    else:
        st.dataframe(df, use_container_width=True, hide_index=False)

def show_home():
    # 🎯 EXPERT FIX: Minimalist "Welcome" Home Page
    st.markdown("<div class='welcome-text'>WELCOME</div>", unsafe_allow_html=True)
    st.markdown("<div class='sub-header'>Civil Hospital HR Management Portal</div>", unsafe_allow_html=True)

def show_regular_staff():
    df = load_data_from_sheet("Sheet1")
    render_smart_table(df, "🩺 Regular Staff Management")

def show_outsource_staff():
    df = load_data_from_sheet("Sheet2")
    render_smart_table(df, "🤝 Outsource Staff Management")

def show_regular_staff_detail():
    df = load_data_from_sheet("Sheet3")
    render_smart_table(df, "📄 Regular Staff Detailed Records")

def show_outsource_staff_detail():
    df = load_data_from_sheet("Sheet4")
    render_smart_table(df, "📋 Outsource Staff Detailed Records")

def show_deputation_staff():
    df = load_data_from_sheet("Sheet5")
    render_smart_table(df, "🔄 Deputation Staff Register")

def show_ward_attendant_list():
    df = load_data_from_sheet("Sheet6")
    render_smart_table(df, "🏥 CH Ward Attendant List")

# ==========================================
# 5. MAIN NAVIGATION CONTROLLER
# ==========================================
def main():
    if not check_login():
        return

    col_a, col_b = st.columns([8, 1])
    with col_a:
        st.markdown(f"<p style='font-size: 1.2rem; color: #1e3a8a;'><strong>Welcome, {st.session_state['current_user']}!</strong></p>", unsafe_allow_html=True)
    with col_b:
        st.button("🚪 Logout", on_click=logout)

    st.markdown("<div class='main-header'>🏢 Civil Hospital HR Dashboard</div>", unsafe_allow_html=True)
    st.markdown("<br>", unsafe_allow_html=True)
    
    selected_page = st.radio(
        "",  
        [
            "🏠 Home",
            "1️⃣ Regular Staff",
            "2️⃣ Outsource Staff",
            "3️⃣ Regular Staff Detail",
            "4️⃣ Outsource Staff Detail",
            "5️⃣ Deputation Staff",
            "6️⃣ CH Ward Attendant"
        ],
        horizontal=True  
    )
    
    st.divider()

    if selected_page == "🏠 Home":
        show_home()
    elif selected_page == "1️⃣ Regular Staff":
        show_regular_staff()
    elif selected_page == "2️⃣ Outsource Staff":
        show_outsource_staff()
    elif selected_page == "3️⃣ Regular Staff Detail":
        show_regular_staff_detail()
    elif selected_page == "4️⃣ Outsource Staff Detail":
        show_outsource_staff_detail()
    elif selected_page == "5️⃣ Deputation Staff":
        show_deputation_staff()
    elif selected_page == "6️⃣ CH Ward Attendant":
        show_ward_attendant_list()

if __name__ == "__main__":
    main()
